# Generated by Django 3.1.7 on 2021-03-27 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210327_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='store.customer'),
        ),
    ]
